### ISSUE TITLE
Doesn't correct kerning with multiple weights in same text string

### ISSUE THREAD

**Issue by scarysnow** [charliecm/figma-fix-sf#2]
It appears that this plugin currently won't allow you to fix kerning when the string of text includes disparate weights of the same size and family.

**Comment by charliecm** [comment]
@scarysnow Thanks for bringing it up. I've added support for texts with mixed properties in the latest version. Let me know if it fixes your issue.

**Comment by scarysnow** [comment]
Awesome, works now! Much appreciated and big time saver.
