### ISSUE TITLE
Support for SF Pro Rounded and New York fonts

### ISSUE THREAD

**Issue by noahmaranesi** [charliecm/figma-fix-sf#3]
Hello!

If you have any extra time, it would be greatly appreciated for the support of SF Pro Rounded and New York fonts to be included in this plugin.

Relevant information:    
**https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography#tracking-values**

Worth noting that the page you've linked ([**#font-usage-and-tracking**](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography#font-usage-and-tracking)) is no longer valid either!

Thanks for your time! 😃

**Comment by charliecm** [comment]
Thanks for writing the issue. The latest version now supports SF Pro Rounded and New York. For New York, it only changes the tracking, not the font (based on size), as I don't know the size ranges it should map to.
